const departments = [
    'Aerospace Engineering',
    'Anthropology',
    'Architecture',
    'Astronomy',
    'Biology',
    'Business Administration',
    'Chemical Engineering',
    'Chemistry',
    'Civil Engineering',
    'Computer Science',
    'Economics',
    'Education',
    'Electrical Engineering',
    'English',
    'Environmental Science',
    'Geology',
    'History',
    'Linguistics',
    'Materials Science and Engineering',
    'Mathematics',
    'Mechanical Engineering',
    'Nursing',
    'Philosophy',
    'Physics',
    'Political Science',
    'Psychology',
    'Public Health',
    'Social Work',
    'Sociology',
  ];

  export default departments;