/*const departments = [
    'AI',
    'Aerospace Engineering',
    'Anthropology',
    'Architecture',
    'Astronomy',
    'Biology',
    'Business Administration',
    'Chemical Engineering',
    'Chemistry',
    'Civil Engineering',
    'Computer Science',
    'Economics',
    'Education',
    'Electrical Engineering',
    'English',
    'Environmental Science',
    'Geology',
    'History',
    'Linguistics',
    'Materials Science and Engineering',
    'Mathematics',
    'Mechanical Engineering',
    'Nursing',
    'Philosophy',
    'Physics',
    'Political Science',
    'Psychology',
    'Public Health',
    'Robotics',
    'Social Work',
    'Sociology',
  ];*/

  const departments = [
    { name: 'Robotics', color: '#FF8C00', progress: 0.2 },
    { name: 'AI',  color: '#228B22', progress: 0.5 },
    { name: 'Medicine', color: '#4682B4', progress: 0.27 },
    { name: 'Economics', color: '#8A2BE2', progress: 0.78 },
    { name: 'Electronics',  color: '#DC143C', progress: 0.24 },
    { name: 'Computer Science', color: '#20B2AA', progress: 0 },
    { name: 'Aerospace',  color: '#556B2F', progress: 0.05 },
    { name: 'Biology', color: '#800000', progress: 0.8 },
    { name: 'Chemistry', color: '#2F4F4F', progress: 0.1 },
    { name: 'Physics', color: '#4B0082', progress: 0.5 },
  ];

  export default departments;