const departments = [
  { display: 'Physics', name: 'Physics' },
  { display: 'Chemistry', name: 'Chemistry' },
  { display: 'Robotics', name: 'Robotics' },
  { display: 'Biology', name: 'Biology' },
  { display: 'Earth Sciences', name: 'EarthSciences' },
  { display: 'Geology', name: 'Geology' },
  { display: 'Oceanography', name: 'Oceanography' },
  { display: 'Astronomy and Space Science', name: 'AstronomyandSpaceScience' },
  { display: 'Environmental Science', name: 'EnvironmentalScience' },
  { display: 'Mathematics', name: 'Mathematics' },
  { display: 'Computer Science', name: 'ComputerScience' },
  { display: 'Statistics', name: 'Statistics' },
  { display: 'Psychology', name: 'Psychology' },
  { display: 'Sociology', name: 'Sociology' },
  { display: 'Anthropology', name: 'Anthropology' },
  { display: 'Economics', name: 'Economics' },
  { display: 'Political Science', name: 'PoliticalScience' },
  { display: 'Engineering', name: 'Engineering' },
  { display: 'Medicine and Health Sciences', name: 'MedicineandHealthSciences' },
  { display: 'Agricultural Sciences', name: 'AgriculturalSciences' },
  { display: 'History', name: 'History' },
  { display: 'Philosophy', name: 'Philosophy' },
  { display: 'Linguistics', name: 'Linguistics' },
  { display: 'Neuroscience', name: 'Neuroscience' },
  { display: 'Biophysics', name: 'Biophysics' },
  { display: 'Data Science', name: 'DataScience' },
  { display: 'Artificial Intelligence', name: 'ArtificialIntelligence' }
];

export default departments;
